name: everything
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_pro: ^1.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  #To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/user/sumon.jpg

   - assets/images/carousel/m1.jpeg
   - assets/images/carousel/m2.jpg
   - assets/images/carousel/m3.png
   - assets/images/carousel/m4.jpg
   - assets/images/carousel/m5.jpg
   - assets/images/carousel/m6.jpeg

   - assets/images/category/shirt.png
   - assets/images/category/tshirt.PNG
   - assets/images/category/pant.PNG
   - assets/images/category/formal.PNG
   - assets/images/category/jersey.PNG
   - assets/images/category/hat.PNG
   - assets/images/category/shoe.PNG

   - assets/images/recent_products/bottle_tshirt.jpg
   - assets/images/recent_products/casual_pant.jpg
   - assets/images/recent_products/cotton_pant.jpeg
   - assets/images/recent_products/hudi.jpeg
   - assets/images/recent_products/light_blue_shirt.jpg
   - assets/images/recent_products/navy_blue_pant.jpg
   - assets/images/recent_products/pants.jpg
   - assets/images/recent_products/patent_tshirt.jpg
   - assets/images/recent_products/red_shirt.jpg
   - assets/images/recent_products/white_shirt.jpg



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
